export const EDITOR_COLORS = [
    { label: "red", value: "#c75d55ff" },
    { label: "blue", value: "#9ec3ff" },
    { label: "green", value: "#719b6f" },
    { label: "yellow", value: "#eee0a8" },
    { label: "purple", value: "#9285ff" },
    { label: "orange", value: "#e3834f" },
    { label: "pink", value: "#c676bd" },
    { label: "cyan", value: "#4ecdff" },
    { label: "lime", value: "#b5be82" },
    { label: "teal", value: "#73aba3" },
    { label: "indigo", value: "#7684b1" },
    { label: "rose", value: "#bb7585" },
    { label: "amber", value: "#d9b88b" },
    { label: "brown", value: "#765e4e" },
    { label: "slate", value: "#6d7277" },
    { label: "gray", value: "#636363" },
    { label: "black", value: "#161616" },
    { label: "white", value: "#dedede" },
]